module_name('luoghi.pl').


%luoghi italiani
fact(1,provincia_sardegna(cagliari),1).
fact(2,provincia_sardegna(sassari),1).
fact(3,provincia_sardegna(nuoro),1).
fact(4,provincia_sardegna(oristano),1).
fact(5,provincia_sardegna(carbonia),1).
fact(6,provincia_sardegna(medio,campidano),1).
fact(7,provincia_sardegna(olbia),1).
fact(8,provincia_sardegna(ogliastra),1).
fact(9,provincia_sicilia(palermo),1).
fact(10,provincia_sicilia(agrigento),1).
fact(11,provincia_sicilia(caltanissetta),1).
fact(12,provincia_sicilia(catania),1).
fact(13,provincia_sicilia(enna),1).
fact(14,provincia_sicilia(messina),1).
fact(15,provincia_sicilia(ragusa),1).
fact(16,provincia_sicilia(siracusa),1).
fact(17,provincia_sicilia(trapani),1).
fact(18,provincia_toscana(arezzo),1).
fact(19,provincia_toscana(massa,carrara),1).
fact(20,provincia_toscana(firenze),1).
fact(21,provincia_toscana(livorno),1).
fact(22,provincia_toscana(grosseto),1).
fact(23,provincia_toscana(lucca),1).
fact(24,provincia_toscana(pisa),1).
fact(25,provincia_toscana(pistoia),1).
fact(26,provincia_toscana(prato),1).
fact(27,provincia_toscana(siena),1).
fact(28,provincia_trentino(trento),1).
fact(29,provincia_trentino(bolzano),1).
fact(30,provincia_umbria(perugia),1).
fact(31,provincia_umbria(terni),1).
fact(32,provincia_veneto(venezia),1).
fact(33,provincia_veneto(belluno),1).
fact(34,provincia_veneto(padova),1).
fact(35,provincia_veneto(rovigo),1).
fact(36,provincia_veneto(treviso),1).
fact(37,provincia_veneto(verona),1).
fact(38,provincia_veneto(vicenza),1).
fact(39,provincia_abruzzo(aquila),1).
fact(40,provincia_abruzzo(chieti),1).
fact(41,provincia_abruzzo(pescara),1).
fact(42,provincia_abruzzo(teramo),1).
fact(43,provincia_basilicata(potenza),1).
fact(44,provincia_basilicata(matera),1).
fact(45,provincia_calabria(reggio,calabria),1).
fact(46,provincia_calabria(catanzaro),1).
fact(47,provincia_calabria(crotone),1).
fact(48,provincia_calabria(vibo,valentia),1).
fact(49,provincia_calabria(cosenza),1).
fact(50,provincia_campania(napoli),1).
fact(51,provincia_campania(avellino),1).
fact(52,provincia_campania(caserta),1).
fact(53,provincia_campania(benevento),1).
fact(54,provincia_campania(salerno),1).
fact(55,provincia_emilia(bologna),1).
fact(56,provincia_emilia(reggio,emilia),1).
fact(57,provincia_emilia(parma),1).
fact(58,provincia_emilia(modena),1).
fact(59,provincia_emilia(ferrara),1).
fact(60,provincia_emilia(forli),1).
fact(61,provincia_emilia(cesena),1).
fact(62,provincia_emilia(piacenza),1).
fact(63,provincia_emilia(ravenna),1).
fact(64,provincia_emilia(rimini),1).
fact(65,provincia_friuli(trieste),1).
fact(66,provincia_friuli(gorizia),1).
fact(67,provincia_friuli(pordenone),1).
fact(68,provincia_friuli(udine),1).
fact(69,provincia_lazio(roma),1).
fact(70,provincia_lazio(latina),1).
fact(71,provincia_lazio(frosinone),1).
fact(72,provincia_lazio(viterbo),1).
fact(73,provincia_lazio(rieti),1).
fact(74,provincia_liguria(genova),1).
fact(75,provincia_liguria(imperia),1).
fact(76,provincia_liguria(la,spezia),1).
fact(77,provincia_liguria(savona),1).
fact(78,provincia_lombardia(milano),1).
fact(79,provincia_lombardia(bergamo),1).
fact(80,provincia_lombardia(brescia),1).
fact(81,provincia_lombardia(como),1).
fact(82,provincia_lombardia(cremona),1).
fact(83,provincia_lombardia(mantova),1).
fact(84,provincia_lombardia(monza),1).
fact(85,provincia_lombardia(pavia),1).
fact(86,provincia_lombardia(sondrio),1).
fact(87,provincia_lombardia(lodi),1).
fact(88,provincia_lombardia(lecco),1).
fact(89,provincia_lombardia(varese),1).
fact(90,provincia_marche(ancona),1).
fact(91,provincia_marche(ascoli,piceno),1).
fact(92,provincia_marche(fermo),1).
fact(93,provincia_marche(macerata),1).
fact(94,provincia_marche(pesaro),1).
fact(95,provincia_marche(urbino),1).
fact(96,provincia_molise(campobasso),1).
fact(97,provincia_molise(isernia),1).
fact(98,provincia_piemonte(torino),1).
fact(99,provincia_piemonte(asti),1).
fact(100,provincia_piemonte(alessandria),1).
fact(101,provincia_piemonte(cuneo),1).
fact(102,provincia_piemonte(novara),1).
fact(103,provincia_piemonte(vercelli),1).
fact(104,provincia_piemonte(verbania),1).
fact(105,provincia_piemonte(biella),1).
fact(106,provincia_aosta(aosta),1).
fact(107,provincia_puglia(bari),1).
fact(108,provincia_puglia(barletta),1).
fact(109,provincia_puglia(andria),1).
fact(110,provincia_puglia(trani),1).
fact(111,provincia_puglia(brindisi),1).
fact(112,provincia_puglia(foggia),1).
fact(113,provincia_puglia(lecce),1).
fact(114,provincia_puglia(taranto),1).


%citt� europa
fact(115,citta_europa(parigi),1).
fact(116,citta_europa(monaco),1).
fact(117,citta_europa(lisbona),1).
fact(118,citta_europa(madrid),1).
fact(119,citta_europa(barcellone),1).
fact(120,citta_europa(valencia),1).
fact(121,citta_europa(maiorca),1).
fact(122,citta_europa(londra),1).
fact(123,citta_europa(manchester),1).
fact(124,citta_europa(dublino),1).
fact(125,citta_europa(zagabria),1).
fact(126,citta_europa(stoccarda),1).
fact(127,citta_europa(sarajevo),1).
fact(128,citta_europa(amsterdam),1).
fact(129,citta_europa(sofia),1).
fact(130,citta_europa(berlgrado),1).
fact(131,citta_europa(budapest),1).
fact(132,citta_europa(bruxelles),1).
fact(133,citta_europa(berna),1).
fact(134,citta_europa(praga),1).
fact(135,citta_europa(vienna),1).
fact(136,citta_europa(ginevra),1).
fact(137,citta_europa(siviglia),1).
fact(138,citta_europa(granada),1).
fact(139,citta_europa(monaco,baviera),1).
fact(140,citta_europa(stoccolma),1).
fact(141,citta_europa(edimburgo),1).
fact(142,citta_europa(glasgow),1).
fact(143,citta_europa(cracovia),1).
fact(144,citta_europa(bergano),1).
fact(145,citta_europa(reykjavik),1).
fact(146,citta_europa(riga),1).
fact(147,citta_europa(liverpool),1).
fact(148,citta_europa(atene),1).
fact(149,citta_europa(porto),1).
fact(150,citta_europa(sofia),1).
fact(151,citta_europa(kiev),1).
fact(152,citta_europa(varsavia),1).
fact(153,citta_europa(minsk),1).
fact(154,citta_europa(francoforte),1).
fact(155,citta_europa(colonia),1).
fact(156,citta_europa(berlino),1).
fact(157,citta_europa(belfast),1).
fact(158,citta_europa(marsiglia),1).
fact(159,citta_europa(lilla),1).
fact(160,citta_europa(hannover),1).
fact(161,citta_europa(brema),1).
fact(162,citta_europa(amburgo),1).
fact(163,citta_europa(malmo),1).
fact(164,citta_europa(helsinki),1).
fact(165,citta_europa(bratislava),1).
fact(166,citta_europa(salonicco),1).
fact(167,citta_europa(vilnius),1).
fact(168,citta_europa(tallinn),1).

%citt� mondo
fact(169,citta_mondo(cipro),1).
fact(170,citta_mondo(baghdad),1).
fact(171,citta_mondo(rivad),1).
fact(172,citta_mondo(doha),1).
fact(173,citta_mondo(sana),1).
fact(174,citta_mondo(muscat),1).
fact(175,citta_mondo(astana),1).
fact(176,citta_mondo(damasco),1).
fact(177,citta_mondo(ulaanbaatar),1).
fact(178,citta_mondo(seoul),1).
fact(179,citta_mondo(pyongyang),1).
fact(180,citta_mondo(tokyo),1).
fact(181,citta_mondo(hong,kong),1).
fact(182,citta_mondo(taipei),1).
fact(183,citta_mondo(manila),1).
fact(184,citta_mondo(bangkok),1).
fact(185,citta_mondo(giacarta),1).
fact(186,citta_mondo(dacca),1).
fact(187,citta_mondo(nuova,deli),1).
fact(188,citta_mondo(islamabad),1).
fact(189,citta_mondo(mosca),1).
fact(190,citta_mondo(ankara),1).
fact(191,citta_mondo(instanbul),1).
fact(192,citta_mondo(tblisi),1).
fact(193,citta_mondo(jerevan),1).
fact(194,citta_mondo(gerusalemme),1).
fact(195,citta_mondo(anuban),1).
fact(196,citta_mondo(nicosia),1).
fact(197,citta_mondo(abu,dhabi),1).
fact(198,citta_mondo(kabul),1).
fact(199,citta_mondo(singapore),1).
fact(200,citta_mondo(rabat),1).
fact(201,citta_mondo(algeri),1).
fact(202,citta_mondo(tunisi),1).
fact(203,citta_mondo(tripoli),1).
fact(204,citta_mondo(il,cairo),1).
fact(205,citta_mondo(bangui),1).
fact(206,citta_mondo(dakar),1).
fact(207,citta_mondo(praia),1).
fact(208,citta_mondo(luanda),1).
fact(209,citta_mondo(citta,capo),1).
fact(210,citta_mondo(maputo),1).
fact(211,citta_mondo(moroni),1).
fact(212,citta_mondo(kampala),1).
fact(213,citta_mondo(pechino),1).
fact(214,citta_mondo(sidney),1).
fact(215,citta_mondo(melbourne),1).
fact(216,citta_mondo(ottawa),1).
fact(217,citta_mondo(toronto),1).
fact(218,citta_mondo(washington),1).
fact(219,citta_mondo(boston),1).
fact(220,citta_mondo(new,york),1).
fact(221,citta_mondo(miami),1).
fact(222,citta_mondo(richmond),1).
fact(223,citta_mondo(minneapolis),1).
fact(224,citta_mondo(oahu),1).
fact(225,citta_mondo(bismark),1).
fact(226,citta_mondo(phoenix),1).
fact(227,citta_mondo(oklahoma),1).
fact(228,citta_mondo(detroit),1).
fact(229,citta_mondo(atlanta),1).
fact(230,citta_mondo(montgomery),1).
fact(231,citta_mondo(topeka),1).
fact(232,citta_mondo(columbia),1).
fact(233,citta_mondo(austindover),1).
fact(234,citta_mondo(trenton),1).
fact(235,citta_mondo(indianapolis),1).
fact(236,citta_mondo(springfield),1).
fact(237,citta_mondo(detroit),1).
fact(238,citta_mondo(denver),1).
fact(239,citta_mondo(guatemala),1).
fact(240,citta_mondo(citta,messico),1).
fact(241,citta_mondo(brasilia),1).
fact(242,citta_mondo(salvador),1).
fact(243,citta_mondo(recife),1).
fact(244,citta_mondo(fortaleza),1).
fact(245,citta_mondo(manaus),1).
fact(246,citta_mondo(caracas),1).
fact(247,citta_mondo(cali),1).
fact(248,citta_mondo(quito),1).
fact(249,citta_mondo(santa,cruz),1).
fact(250,citta_mondo(sao,paulo),1).
fact(251,citta_mondo(san,paolo),1).
fact(252,citta_mondo(rio,janeiro),1).
fact(253,citta_mondo(montevideo),1).
fact(254,citta_mondo(buenos,aires),1).
fact(255,citta_mondo(santiago),1).
fact(256,citta_mondo(asunsion),1).
fact(257,citta_mondo(lima),1).
fact(258,citta_mondo(belem),1).
fact(259,citta_mondo(bogota),1).
fact(260,citta_mondo(monterrey),1).
fact(261,citta_mondo(avana),1).

				
%regole per luoghi italiani
rule(2,[citta(X,sardegna)],and([tag(nom(X),pos(_),FX),provincia_sardegna(X)]),1,1).
rule(3,[citta(X1,sicilia)],and([tag(nom(X1),pos(_),FX),provincia_sicilia(X1)]),1,1).
rule(4,[citta(X2,toscana)],and([tag(nom(X2),pos(_),FX),provincia_toscana(X2)]),1,1).
rule(5,[citta(X3,trentino)],and([tag(nom(X3),pos(_),FX),provincia_trentino(X3)]),1,1).
rule(6,[citta(X4,umbria)],and([tag(nom(X4),pos(_),FX),provincia_umbria(X4)]),1,1).
rule(7,[citta(X5,veneto)],and([tag(nom(X5),pos(_),FX),provincia_veneto(X5)]),1,1).
rule(8,[citta(X6,abruzzo)],and([tag(nom(X6),pos(_),FX),provincia_abruzzo(X6)]),1,1).
rule(9,[citta(X7,basilicata)],and([tag(nom(X7),pos(_),FX),provincia_basilicata(X7)]),1,1).
rule(10,[citta(X8,calabria)],and([tag(nom(X8),pos(_),FX),provincia_calabria(X8)]),1,1).
rule(11,[citta(X9,campania)],and([tag(nom(X9),pos(_),FX),provincia_campania(X9)]),1,1).
rule(12,[citta(X10,emilia)],and([tag(nom(X10),pos(_),FX),provincia_emilia(X10)]),1,1).
rule(13,[citta(X11,friuli)],and([tag(nom(X11),pos(_),FX),provincia_friuli(X11)]),1,1).
rule(14,[citta(X12,lazio)],and([tag(nom(X12),pos(_),FX),provincia_lazio(X12)]),1,1).
rule(15,[citta(X13,liguria)],and([tag(nom(X13),pos(_),FX),provincia_liguria(X13)]),1,1).
rule(16,[citta(X14,lombardia)],and([tag(nom(X14),pos(_),FX),provincia_lombardia(X14)]),1,1).
rule(17,[citta(X15,marche)],and([tag(nom(X15),pos(_),FX),provincia_marche(X15)]),1,1).
rule(18,[citta(X16,piemonte)],and([tag(nom(X16),pos(_),FX),provincia_piemonte(X16)]),1,1).
rule(19,[citta(X17,aosta)],and([tag(nom(X17),pos(_),FX),provincia_aosta(X17)]),1,1).
rule(20,[citta(X18,puglia)],and([tag(nom(X18),pos(_),FX),provincia_puglia(X18)]),1,1).
rule(21,[citta(X19,molise)],and([tag(nom(X19),pos(_),FX),provincia_molise(X19)]),1,1).

rule(22,[citta(X,sardegna)],and([tag(ogg(X20),pos(_),FX),provincia_sardegna(X20)]),1,1).
rule(23,[citta(X1,sicilia)],and([tag(ogg(X21),pos(_),FX),provincia_sicilia(X21)]),1,1).
rule(24,[citta(X2,toscana)],and([tag(ogg(X22),pos(_),FX),provincia_toscana(X22)]),1,1).
rule(25,[citta(X3,trentino)],and([tag(ogg(X23),pos(_),FX),provincia_trentino(X23)]),1,1).
rule(26,[citta(X4,umbria)],and([tag(ogg(X24),pos(_),FX),provincia_umbria(X24)]),1,1).
rule(27,[citta(X5,veneto)],and([tag(ogg(X25),pos(_),FX),provincia_veneto(X25)]),1,1).
rule(28,[citta(X6,abruzzo)],and([tag(ogg(X26),pos(_),FX),provincia_abruzzo(X26)]),1,1).
rule(29,[citta(X7,basilicata)],and([tag(ogg(X27),pos(_),FX),provincia_basilicata(X27)]),1,1).
rule(30,[citta(X8,calabria)],and([tag(ogg(X28),pos(_),FX),provincia_calabria(X28)]),1,1).
rule(31,[citta(X9,campania)],and([tag(ogg(X29),pos(_),FX),provincia_campania(X29)]),1,1).
rule(32,[citta(X10,emilia)],and([tag(ogg(X30),pos(_),FX),provincia_emilia(X30)]),1,1).
rule(33,[citta(X11,friuli)],and([tag(ogg(X31),pos(_),FX),provincia_friuli(X31)]),1,1).
rule(34,[citta(X12,lazio)],and([tag(ogg(X32),pos(_),FX),provincia_lazio(X32)]),1,1).
rule(35,[citta(X13,liguria)],and([tag(ogg(X33),pos(_),FX),provincia_liguria(X33)]),1,1).
rule(36,[citta(X14,lombardia)],and([tag(ogg(X34),pos(_),FX),provincia_lombardia(X34)]),1,1).
rule(37,[citta(X15,marche)],and([tag(ogg(X35),pos(_),FX),provincia_marche(X35)]),1,1).
rule(38,[citta(X16,piemonte)],and([tag(ogg(X36),pos(_),FX),provincia_piemonte(X36)]),1,1).
rule(39,[citta(X17,aosta)],and([tag(ogg(X37),pos(_),FX),provincia_aosta(X37)]),1,1).
rule(40,[citta(X18,puglia)],and([tag(ogg(X38),pos(_),FX),provincia_puglia(X38)]),1,1).
rule(41,[citta(X19,molise)],and([tag(ogg(X39),pos(_),FX),provincia_molise(X39)]),1,1).

rule(42,luogo_italiano(C,Y),and([citta(C,Y)]),1,1).

%regole per luoghi europei
rule(43,citta_europea(E),and([tag(nom(E),pos(_),FX),citta_europa(E)]),1,1).
rule(44,citta_europea(E),and([tag(ogg(E),pos(_),FX),citta_europa(E)]),1,1).


%regole per luoghi mondiali
rule(45,citta_mondiale(M),and([tag(nom(M),pos(_),FX),citta_mondo(M)]),1,1).
rule(46,citta_mondiale(M),and([tag(ogg(M),pos(_),FX),citta_mondo(M)]),1,1).
