au(ottantuno).
au(sessantadue).
au(quindici).
au(cinquantatre).
au(ventiquattro).
au(quattro).
au(settantotto).
au(nove).
au(venticinque).
au(ventitre).
au(cinquantasette).
au(cinquantotto).
au(sessantaquattro).
au(settantaquattro).
au(settantasette).
au(ventidue).
au(cinquantuno).
au(cinquantaquattro).
au(settantacinque).
au(settantadue).
au(sedici).
au(dieci).
au(settantasei).
au(tre).
au(cinque).
au(ventisei).
au(ventisette).
au(venti).
au(sessantuno).
au(uno).
au(dodici).
au(sei).
au(settantuno).
au(diciasette).
au(cinquantadue).
au(ottanta).
au(due).
au(sette).
au(settanta).
